#!/usr/bin/env python3

ROLES = {

# Goalkeeper Roles
'Goalkeeper':     [{'Defend':  [['Aerial Reach', 'Command of Area', 'Communication', 'Handling', 'Kicking', 'Reflexes', 'Concentration', 'Positioning', 'Agility'], 
				                ['One On Ones', 'Throwing', 'Anticipation', 'Decisions']]}]
'Sweeper Keeper': [{'Defend':  [['Command of Area', 'Kicking', 'One On Ones', 'Reflexes', 'Anticipation', 'Concentration', 'Positioning', 'Agility'],
							    ['Aerial Reach', 'Communication', 'First Touch', 'Handling', 'Passing', 'Rushing Out (Tendency)', 'Throwing', 'Composure', 'Decisions', 'Vision', 'Acceleration']]}, 
				   {'Support': [['Command of Area', 'Kicking', 'One On Ones', 'Reflexes', 'Rushing Out (Tendency)', 'Anticipation', 'Composure', 'Concentration', 'Positioning', 'Agility'],
							    ['Aerial Reach', 'Communication', 'First Touch', 'Handling', 'Passing', 'Throwing', 'Decisions', 'Vision', 'Acceleration']]}, 
				   {'Attack':  [['Command of Area', 'Kicking', 'One On Ones', 'Reflexes', 'Rushing Out (Tendency)', 'Anticipation', 'Composure', 'Concentration', 'Positioning', 'Agility'],
							    ['Aerial Reach', 'Communication', 'Eccentricity', 'First Touch', 'Handling', 'Passing', 'Throwing', 'Decisions', 'Vision', 'Acceleration']]}]

# Defending Roles
'Wide Centre-Back':        [{'Defend':  [['Crossing', 'Heading', 'Marking', 'Tackling', 'Positioning', 'Jumping Reach', 'Stamina', 'Strength'], 
										 ['Dribbling', 'Agression', 'Anticipation', 'Bravery', 'Composure', 'Concentration', 'Decisions', 'Work Rate', 'Pace']]}, 
							{'Support': [['Crossing', 'Dribbling', 'Heading', 'Marking', 'Tackling', 'Positioning', 'Jumping Reach', 'Pace', 'Stamina', 'Strength'], 
										 ['Agression', 'Anticipation', 'Bravery', 'Composure', 'Concentration', 'Decisions', 'Off The Ball', 'Work Rate']]}, 
							{'Attack':  [['Crossing', 'Dribbling', 'Heading', 'Marking', 'Tackling', 'Off The Ball', 'Jumping Reach', 'Pace', 'Stamina', 'Strength'], 
										 ['Agression', 'Anticipation','Bravery', 'Composure', 'Concentration', 'Decisions', 'Positioning', 'Work Rate']]}]
'Central Defender':        [{'Defend':  [['Heading', 'Marking', 'Tackling', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['Agression', 'Anticipation', 'Bravery', 'Composure', 'Concentration', 'Decisions', 'Pace']]}, 
							{'Stopper': [['Heading', 'Tackling', 'Agression', 'Bravery', 'Decisions', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['Marking', 'Anticipation', 'Composure', 'Concentration']]},
							{'Cover':   [['Marking', 'Tackling', 'Anticipation', 'Concentration', 'Decisions', 'Positioning', 'Pace'],
										 ['Heading', 'Bravery', 'Composure', 'Jumping Reach', 'Strength']]}]
'Libero':                  [{'Support': [['First Touch', 'Marking', 'Passing', 'Tackling', 'Anticipation', 'Composure', 'Concentration', 'Decisions', 'Positioning', 'Teamwork', 'Vision', 'Pace'],
										 ['Dribbling', 'Heading', 'Technique', 'Bravery', 'Flair', 'Agility', 'Balance', 'Jumping Reach', 'Stamina', 'Strength']]}, 
							{'Attack':  [['Dribbling', 'First Touch', 'Marking', 'Passing', 'Tackling', 'Anticipation', 'Composure', 'Concentration', 'Decisions', 'Flair', 'Positioning', 'Teamwork', 'Vision', 'Pace'],
										 ['Heading', 'Long Shots', 'Technique', 'Bravery', 'Acceleration', 'Agility', 'Balance', 'Jumping Reach', 'Stamina', 'Strength']]}],
'Ball Playing Defender':   [{'Defend':  [['Heading', 'Marking', 'Passing', 'Tackling', 'Composure', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['First Touch', 'Technique', 'Agression', 'Anticipation', 'Bravery', 'Concentration', 'Decisions', 'Vision', 'Pace']]}, 
							{'Stopper': [['Heading', 'Passing', 'Tackling', 'Agression', 'Bravery', 'Composure', 'Decisions', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['First Touch', 'Marking', 'Technique', 'Anticipation', 'Concentration', 'Vision']]},
							{'Cover':   [['Marking', 'Passing', 'Tackling', 'Anticipation', 'Composure', 'Concentration', 'Decisions', 'Positioning', 'Pace'],
										 ['First Touch', 'Heading', 'Technique', 'Bravery', 'Vision', 'Jumping Reach', 'Strength']]}],
'No-Nonsense Centre-Back': [{'Defend':  [['Heading', 'Marking', 'Tackling', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['Agression', 'Anticipation', 'Bravery', 'Concentration', 'Pace']]},
						    {'Stopper': [['Heading', 'Tackling', 'Agression', 'Bravery', 'Positioning', 'Jumping Reach', 'Strength'],
										 ['Marking', 'Anticipation', 'Concentration']]},
						    {'Cover':   [['Marking', 'Tackling', 'Anticipation', 'Concentration', 'Positioning', 'Pace'],
										 ['Heading', 'Bravery', 'Jumping Reach', 'Strength']]}],

# Midfield Roles
'Defensive Midfielder':    [{'Defend':  [[],
										 []]}, 
							{'Support': [[],
										 []]}],
'Deep Lying Playmaker':    [{'Defend':  [[],
										 []]}, 
							{'Support': [[],
										 []]}],
'Ball Winning Midfielder': [{'Defend':  [[],
										 []]}, 
							{'Support': [[],
										 []]}],
'Anchor Man':              [{'Defend':  [[],
										 []]}],
'Half Back':               [{'Defend':  [[],
										 []]}],
'Regista':                 [{'Support': [[],
										 []]}],
'Roaming Playmaker':       [{'Support': [[],
										 []]}],
'Segundo Volante':         [{'Support': [[],
										 []]}, 
							{'Attack':  [[],
										 []]}],
'Central Midfielder':      [{'Defend':  [[],
										 []]},
							{'Support': [[],
										 []]},
							{'Attack':  [[],
										 []]}],
'Box-to-Box Midfielder':   [{'Support': [[],
										 []]}],
'Advanced Playmaker':      [{'Support': [[],
										 []]}, 
							{'Attack':  [[],
										 []]}],
'Mezzala':                 [{'Support': [[],
										 []]}, 
							{'Attack':  [[],
										 []]}],
'Carrilero':               [{'Support': [[],
										 []]}],

# Flank Roles
'Full Back':             [{'Defend':  [[],
									   []]}, 
						  {'Support': [[],
						  			   []]},
						  {'Attack':  [[],
						  			   []]}],
'Wing Back':             [{'Defend':  [[],
									   []]}, 
						  {'Support': [[],
						  			   []]},
						  {'Attack':  [[],
						  			   []]}],
'No-Nonsense Full Back': [{'Defend':  [[],
									   []]}],
'Complete Wing Back':    [{'Support': [[],
									   []]}, 
						  {'Attack':  [[],
									   []]}],
'Inverted Wing Back':    [{'Defend':  [[],
									   []]}, 
						  {'Support': [[],
						  			   []]},
						  {'Attack':  [[],
						  			   []]}],
'Wide Midfielder':       [{'Defend':  [[],
									   []]}, 
						  {'Support': [[],
						  			   []]},
						  {'Attack':  [[],
						  			   []]}],
'Winger':                [{'Support': [[],
									   []]}, 
						  {'Attack':  [[],
									   []]}],
'Defensive Winger':      [{'Defend':  [[],
									   []]}, 
						  {'Support': [[],
									   []]}]
}


if __name__ == '__main__':

	for role in roles:
		print(role)